version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: budgetly
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
